version: '3.8'

services:

  bank-rest:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - JWT_LIFETIME=30m
      - ENCODER_SECRET=QMULq8kR3pVbV0w9q8e5j7nC2vF4hXyD
      - ENCODER_ALGORITM=AES
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=trace
    depends_on:
      - postgres
    restart: unless-stopped

  # Сервис с PostgreSQL базой данных
  postgres:
    container_name: bank_rest_db
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    restart: unless-stopped



# Volume для сохранения данных БД
volumes:
  postgres_data:
