spring:
  application:
    name: bank-cards
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: ${DATASOURCE_PROTOCOL}://${DEV_IP_ADDRESS}:${DATASOURCE_PORT}/${DATASOURCE_NAME}?${DATASOURCE_PROPERTIES}
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
    change-log: classpath:db/migration/db.changelog-master.yml

server:
  port: 8080


